import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Password generator app</title>
        <meta
          name="Password generator app"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello, password generator app</h1>
      </main>
    </div>
  );
};

export default Home;
